#!/usr/bin/env python3
"""Writes tools/shots.txt from data/art.json shots.list (spec sprite-view.md section 12).

Each entry becomes one `name | args` line for tools/shot.gd. Entries whose setup or view flags are not built yet
(being setups, selection, roofs) are written as comments so shots.sh skips them; add the name to READY as each step lands.
Extra lines (EXTRA) are shots that are not in the spec list. Showcase shots hide the text HUD so it does not cover the
buildings (--view hud=false).
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ART = json.loads((HERE.parent / "data" / "art.json").read_text())

READY_SETUPS = {"founders", "showcase", "showcase_offline", "showcase_door_habitat", "showcase_door_workshop"}
READY_VIEW_KEYS = {"debug_map"}
# Shots that need beings, footprints or roofs (steps 14 to 16): written as comments until those steps land.
PENDING_IDS = {"s20_mining_trip", "s21_footprints_sol3", "s26_roof_zoom_cut"}
HUD_OFF_SETUPS = READY_SETUPS - {"founders"}

EXTRA = [
    ("landing_dawn", "--seed 42 --steps 0 --hour 6 --zoom 2"),
    ("landing_night", "--seed 42 --steps 0 --hour 23 --zoom 2"),
    ("sol20_seed42", "--seed 42 --steps 9864 --hour 12 --zoom 2"),
    ("sol100_zoom_out", "--seed 42 --steps 49320 --hour 12 --zoom 0.6 --center colony --view hud=false"),
]


def args_for(s):
    parts = [f"--seed {s['seed']}"]
    if "steps" in s:
        parts.append(f"--steps {s['steps']}")
    if "until" in s:
        parts.append("--until " + ",".join(f"{k}={v}" for k, v in s["until"].items()))
    if "hour" in s:
        parts.append(f"--hour {s['hour']}")
    parts.append(f"--setup {s['setup']}")
    parts.append(f"--zoom {s['zoom']}")
    parts.append(f"--center {s['center']}")
    view = dict(s.get("view", {}))
    if s["setup"] in HUD_OFF_SETUPS or "until" in s:
        view["hud"] = False
    if view:
        parts.append("--view " + ",".join(f"{k}={str(v).lower() if isinstance(v, bool) else v}" for k, v in view.items()))
    return " ".join(parts)


def main():
    lines = ["# name | args for tools/shot.gd (--out is added by shots.sh). Generated by tools/shots_from_art.py"]
    for s in ART["shots"]["list"]:
        ready = s["id"] not in PENDING_IDS and s["setup"] in READY_SETUPS and set(s.get("view", {})) <= READY_VIEW_KEYS
        line = f"{s['id']} | {args_for(s)}"
        lines.append(line if ready else "# pending a later step: " + line)
    for name, args in EXTRA:
        lines.append(f"{name} | {args}")
    (HERE / "shots.txt").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
