#!/usr/bin/env python3
"""Writes tools/shots.txt from data/art.json shots.list (spec sprite-view.md section 12).

Each entry becomes one `name | args` line for tools/shot.gd. Entries whose setup or view flags are not built yet
(being setups, selection, roofs) are written as comments so shots.sh skips them; add the name to READY as each step lands.
Extra lines (EXTRA) are shots that are not in the spec list. Showcase shots hide the text HUD so it does not cover the
buildings (--view hud=false).
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ART = json.loads((HERE.parent / "data" / "art.json").read_text())

READY_SETUPS = {"founders", "showcase", "showcase_offline", "showcase_door_habitat", "showcase_door_workshop",
                "showcase_suits", "showcase_born_pair", "showcase_lamp_dusk", "showcase_interior_habitat",
                "showcase_interior_comms", "showcase_interior_workshop"}
READY_VIEW_KEYS = {"debug_map", "select", "peek", "art_set"}
# Shots whose step has not landed: written as comments until it does.
PENDING_IDS = set()
# Review nit 2: a lamp shot at exactly 19:00 is unreliable (--hour lands within 0.025 h), so the dusk shot uses 19.5.
HOUR_OVERRIDES = {"s17_suits_dusk_lamps": 19.5}
# The footprint count is reached at night, where the dark prints cannot be seen: step on to noon (prints last 2.5 sols).
HOUR_ADDED = {"s21_footprints_sol3": 12}
HUD_OFF_SETUPS = READY_SETUPS - {"founders"}

EXTRA = [
    ("landing_dawn", "--seed 42 --steps 0 --hour 6 --zoom 2"),
    ("landing_night", "--seed 42 --steps 0 --hour 23 --zoom 2"),
    ("sol20_seed42", "--seed 42 --steps 9864 --hour 12 --zoom 2"),
    ("lamp_dusk_1930", "--seed 42 --hour 19.5 --setup showcase_lamp_dusk --zoom 6.0 --center showcase_beings --view hud=false"),
    ("lamp_night_2300", "--seed 42 --hour 23 --setup showcase_lamp_dusk --zoom 6.0 --center showcase_beings --view hud=false"),
    ("footprints_close", "--seed 42 --steps 1480 --until footprints_ge=20 --hour 12 --setup founders --zoom 6.0 --center footprints --view hud=false"),
    ("sol100_zoom_out", "--seed 42 --steps 49320 --hour 12 --zoom 0.6 --center colony --view hud=false"),
]


def args_for(s):
    parts = [f"--seed {s['seed']}"]
    if "steps" in s:
        parts.append(f"--steps {s['steps']}")
    if "until" in s:
        parts.append("--until " + ",".join(f"{k}={v}" for k, v in s["until"].items()))
    if "hour" in s:
        parts.append(f"--hour {HOUR_OVERRIDES.get(s['id'], s['hour'])}")
    elif s["id"] in HOUR_ADDED:
        parts.append(f"--hour {HOUR_ADDED[s['id']]}")
    parts.append(f"--setup {s['setup']}")
    parts.append(f"--zoom {s['zoom']}")
    parts.append(f"--center {s['center']}")
    view = dict(s.get("view", {}))
    if s["setup"] in HUD_OFF_SETUPS or "until" in s:
        view["hud"] = False
    if view:
        parts.append("--view " + ",".join(f"{k}={str(v).lower() if isinstance(v, bool) else v}" for k, v in view.items()))
    return " ".join(parts)


def main():
    lines = ["# name | args for tools/shot.gd (--out is added by shots.sh). Generated by tools/shots_from_art.py"]
    for s in ART["shots"]["list"]:
        ready = s["id"] not in PENDING_IDS and s["setup"] in READY_SETUPS and set(s.get("view", {})) <= READY_VIEW_KEYS
        line = f"{s['id']} | {args_for(s)}"
        lines.append(line if ready else "# pending a later step: " + line)
    for name, args in EXTRA:
        lines.append(f"{name} | {args}")
    (HERE / "shots.txt").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
